// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type GuildSetting struct {
	GuildID      string
	LogChannelID string
	UpdatedAt    sql.NullTime
}

type ModLog struct {
	ID        int64
	GuildID   string
	UserID    string
	Action    string
	Reason    sql.NullString
	CreatedAt sql.NullTime
}

type ServerLevel struct {
	GuildID    string
	UserID     string
	Xp         int64
	Level      int64
	LastXpGain time.Time
}
