// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server-levels.sql

package database

import (
	"context"
	"time"
)

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT user_id, xp, level
FROM server_levels
WHERE guild_id = ?
ORDER BY xp DESC
LIMIT 10
`

type GetLeaderboardRow struct {
	UserID string
	Xp     int64
	Level  int64
}

func (q *Queries) GetLeaderboard(ctx context.Context, guildID string) ([]GetLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboard, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(&i.UserID, &i.Xp, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRank = `-- name: GetUserRank :one
SELECT xp, level
FROM server_levels
WHERE guild_id = ? AND user_id = ?
`

type GetUserRankParams struct {
	GuildID string
	UserID  string
}

type GetUserRankRow struct {
	Xp    int64
	Level int64
}

func (q *Queries) GetUserRank(ctx context.Context, arg GetUserRankParams) (GetUserRankRow, error) {
	row := q.db.QueryRowContext(ctx, getUserRank, arg.GuildID, arg.UserID)
	var i GetUserRankRow
	err := row.Scan(&i.Xp, &i.Level)
	return i, err
}

const updateUserXP = `-- name: UpdateUserXP :one
INSERT INTO server_levels (guild_id, user_id, xp, level, last_xp_gain)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(guild_id, user_id) DO UPDATE SET
    xp = excluded.xp,
    level = excluded.level,
    last_xp_gain = excluded.last_xp_gain
RETURNING guild_id, user_id, xp, level, last_xp_gain
`

type UpdateUserXPParams struct {
	GuildID    string
	UserID     string
	Xp         int64
	Level      int64
	LastXpGain time.Time
}

func (q *Queries) UpdateUserXP(ctx context.Context, arg UpdateUserXPParams) (ServerLevel, error) {
	row := q.db.QueryRowContext(ctx, updateUserXP,
		arg.GuildID,
		arg.UserID,
		arg.Xp,
		arg.Level,
		arg.LastXpGain,
	)
	var i ServerLevel
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.Xp,
		&i.Level,
		&i.LastXpGain,
	)
	return i, err
}
