// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package database

import (
	"context"
	"database/sql"
)

const getLogChannel = `-- name: GetLogChannel :one
SELECT log_channel_id FROM guild_settings
WHERE guild_id = ? LIMIT 1
`

func (q *Queries) GetLogChannel(ctx context.Context, guildID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLogChannel, guildID)
	var log_channel_id string
	err := row.Scan(&log_channel_id)
	return log_channel_id, err
}

const getUserModLogs = `-- name: GetUserModLogs :many
SELECT action, reason, created_at FROM mod_logs
WHERE guild_id = ? AND user_id = ?
ORDER BY created_at DESC
`

type GetUserModLogsParams struct {
	GuildID string
	UserID  string
}

type GetUserModLogsRow struct {
	Action    string
	Reason    sql.NullString
	CreatedAt sql.NullTime
}

func (q *Queries) GetUserModLogs(ctx context.Context, arg GetUserModLogsParams) ([]GetUserModLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserModLogs, arg.GuildID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserModLogsRow
	for rows.Next() {
		var i GetUserModLogsRow
		if err := rows.Scan(&i.Action, &i.Reason, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertModLog = `-- name: InsertModLog :exec
INSERT INTO mod_logs (guild_id, user_id, action, reason)
VALUES (?, ?, ?, ?)
`

type InsertModLogParams struct {
	GuildID string
	UserID  string
	Action  string
	Reason  sql.NullString
}

func (q *Queries) InsertModLog(ctx context.Context, arg InsertModLogParams) error {
	_, err := q.db.ExecContext(ctx, insertModLog,
		arg.GuildID,
		arg.UserID,
		arg.Action,
		arg.Reason,
	)
	return err
}

const setLogChannel = `-- name: SetLogChannel :exec
INSERT INTO guild_settings (guild_id, log_channel_id)
VALUES (?, ?)
ON CONFLICT(guild_id) DO UPDATE SET
    log_channel_id = excluded.log_channel_id,
    updated_at = CURRENT_TIMESTAMP
`

type SetLogChannelParams struct {
	GuildID      string
	LogChannelID string
}

func (q *Queries) SetLogChannel(ctx context.Context, arg SetLogChannelParams) error {
	_, err := q.db.ExecContext(ctx, setLogChannel, arg.GuildID, arg.LogChannelID)
	return err
}
